---
client_secret: l0KI0nz6v072ZRNPHzR8QKKMNLbLxfa8
client_id: 5sf8m1j7tz46hezbe6tr3g59w1u87di1
accounts:
  kamil:
    code: oo1FMNAWWe7PWOZlAX3KntGTpPSe4Iwm
    token: ApQKvFFlVppHThOviDqDyyZnBQKblGNr
    refresh_token: eK1uAvXkMgyJEraJyI7nO0FtaehSZoqlAlF4RIQv3f7sOni3XCXLjSPr7WNzX6uG
    timestamp: 1369752100
